# workflow configuration where it automatically runs tests for both backend and frontend when a PR has been created to main and dev branch 
name: CI Pipeline

# the trigger - when pull request is created on those branches only
on:
    pull_request:
        branches: [main, dev]

jobs:
    # this is for backend check only 
    # ubuntu latest - GitHub will uses linux machine - better and minimize build minutes 
    backend-test:
        runs-on: ubuntu-latest
        steps:
        # provide job access to the code in the repo 
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            # these lines tell Github Actions which installer and distribution to install
            java-version: '17'
            distribution: 'temurin'
            # maven (pom.xml) will be used to download dependencies and will be cache so speed up builds 
            cache: 'maven'
            cache-dependency-path: apps/backend/pom.xml
        - name: Build with Maven
            # maven to used only for backend module
            # '-am' is for buidling required dependencies
            # 'clean' is to ensure that removes complied files
            # 'verify' is to validate that it compiles code and runs all tests 
          run: mvn -pl apps/backend -am clean verify 

    frontend-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '24' # node 20 will be deprecated
                # uses yarn not npm 
                cache: 'yarn'
                cache-dependency-path: apps/frontend/yarn.lock
            - name: Install & Test (Yarn)
                # install all dependencies - Angular and builds node_modules
                # frozen-lockfile - prevent changes to lockfile 
                # watch=false and --browsers - runs tests in chrome without opening a visible browser window
              run: | 
                cd apps/frontend 
                yarn install --frozen-lockfile 
                yarn test --watch=false --browsers=ChromeHeadless



